# Generated by Django 5.1.4 on 2024-12-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_title", models.CharField(max_length=200)),
                ("task_description", models.TextField(blank=True)),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("To-Do", "To-Do"),
                            ("In Progress", "In Progress"),
                            ("Done", "Done"),
                        ],
                        default="To-Do",
                        max_length=50,
                    ),
                ),
                ("task_created_at", models.DateTimeField(auto_now_add=True)),
                ("task_closed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
