# Generated by Django 5.1.4 on 2024-12-16 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Deadline"),
        ),
        migrations.AddField(
            model_name="task",
            name="task_priority",
            field=models.CharField(
                choices=[("Low", "Low"), ("Medium", "Medium"), ("High", "High")],
                default="Medium",
                max_length=20,
                verbose_name="Priority",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="task_updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("To-Do", "To-Do"),
                    ("In Progress", "In Progress"),
                    ("Done", "Done"),
                ],
                default="To-Do",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
    ]
