# Generated by Django 5.1.4 on 2024-12-18 13:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"verbose_name": "Board", "verbose_name_plural": "Boards"},
        ),
        migrations.AlterModelOptions(
            name="column",
            options={
                "ordering": ["column_order"],
                "verbose_name": "Column",
                "verbose_name_plural": "Columns",
            },
        ),
        migrations.AddField(
            model_name="board",
            name="board_created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="board",
            name="board_created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_boards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
            preserve_default=False,
        ),
    ]
