# Generated by Django 5.1.4 on 2024-12-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_alter_board_options_alter_column_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="board_users",
            new_name="board_members",
        ),
    ]
